server:
  port: 8001
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
spring:
  # 数据库相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost/sote?characterEncoding=utf8&useSSL=false
    # druid连接池配置
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-return: false
      test-on-borrow: true
      test-while-idle: true
      filters: stat,wall
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: 123
        enabled: true
      use-global-data-source-stat: true
#  redis:
#    host:
#    port:
#    password:
#    client-type: jedis
#    jedis:
#      pool:
#        max-active: 10
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.upc.eden: debug
debug:
  true
