server:
  port: 10010
spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://124.222.238.194:10010/auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"
      - "/**"
ribbon:
  eager-load:
    enabled: true
    clients:
      - auth-service
auth-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule