
name: Docker-Images-Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
         java-version: 11
     - uses: docker/setup-buildx-action@v1
     - uses: actions/setup-node@v1
       with:
         node-version: 12.x
     # 安装maven依赖
     - name: Maven Clean Install
       run: |
         echo '=====开始mvn clean====='
         mvn clean
         echo '=====开始mvn install&&package====='
         mvn install -DskipTests=true && mvn package -DskipTests=true
         
     - name: Build Server Images
       run: |
   
        echo '======= 开始构建后端镜像 ======='
        echo '======= 开始构建sote-auth-9401 ======='
        cd sote-auth-9401
        mvn docker:build
        cd ..
        
        echo '======= 开始构建sote-gateway-10010 ======='
        cd sote-gateway-10010
        mvn docker:build
        cd ..
        
     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          
     - name: push Images to DockerHub
       run: |
          docker images
          echo '======= 开始上传镜像 ======='
          
          echo '======= 开始上传sote-auth ======='
          docker push 17864230511/sote-auth-9401
          
          echo '======= 开始上传sote-gateway ======='
          docker push 17864230511/sote-gateway-10010
          
          
          echo '=====镜像上传结束====='
